repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Git style
    - id: check-added-large-files
      name: "[pre-commit/pre-commit-hooks]check-added-large-files"
    - id: check-merge-conflict
      name: "[pre-commit/pre-commit-hooks]check-merge-conflict"
    - id: check-vcs-permalinks
      name: "[pre-commit/pre-commit-hooks]check-vcs-permalinks"
    - id: forbid-new-submodules
      name: "[pre-commit/pre-commit-hooks]forbid-new-submodules"

    # Common errors
    - id: end-of-file-fixer
      name: "[pre-commit/pre-commit-hooks]end-of-file-fixer"
    - id: trailing-whitespace
      name: "[pre-commit/pre-commit-hooks]trailing-whitespace"
      args: ['--markdown-linebreak-ext=md']
      exclude: CHANGELOG.md
    - id: check-yaml
      name: "[pre-commit/pre-commit-hooks]check-yaml"
      args: ['--unsafe']
    - id: check-json
      name: "[pre-commit/pre-commit-hooks]check-json"
    - id: pretty-format-json
      name: "[pre-commit/pre-commit-hooks]pretty-format-json"
      args: ['--autofix', '--no-ensure-ascii', '--no-sort-keys']
    - id: check-merge-conflict
      name: "[pre-commit/pre-commit-hooks]check-merge-conflict"
    - id: check-executables-have-shebangs
      name: "[pre-commit/pre-commit-hooks]check-executables-have-shebangs"

    # Cross platform
    - id: check-case-conflict
      name: "[pre-commit/pre-commit-hooks]check-case-conflict"
    - id: mixed-line-ending
      name: "[pre-commit/pre-commit-hooks]mixed-line-ending"
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      name: "[pre-commit/pre-commit-hooks]detect-aws-credentials"
      args: ['--allow-missing-credentials']
    - id: detect-private-key
      name: "[pre-commit/pre-commit-hooks]detect-private-key"

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      name: "[terraform-docs/terraform-docs]terraform-docs-go"
      args: ["markdown", "table", "--output-file=./docs/terraform.md", "--config=./.terraform-docs.yml", "./"]

- repo: https://github.com/Infrastrukturait/pre-commit-readmegen
  rev: v0.3.0
  hooks:
    - id: readmegen
      name: "[Infrastrukturait/pre-commit-readmegen]readmegen"

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
    - id: terraform_fmt
      name: "[antonbabenko/pre-commit-terraform]terraform_fmt"
    - id: terraform_validate
      name: "[antonbabenko/pre-commit-terraform]terraform_validate"
    - id: terraform_tflint
      name: "[antonbabenko/pre-commit-terraform]terraform_tflint"
      args:
      - '--args=--only=terraform_deprecated_interpolation'
      - '--args=--only=terraform_deprecated_index'
      - '--args=--only=terraform_unused_declarations'
      - '--args=--only=terraform_comment_syntax'
      - '--args=--only=terraform_documented_outputs'
      - '--args=--only=terraform_documented_variables'
      - '--args=--only=terraform_typed_variables'
      - '--args=--only=terraform_module_pinned_source'
      - '--args=--only=terraform_naming_convention'
      - '--args=--only=terraform_required_version'
      - '--args=--only=terraform_required_providers'
      - '--args=--only=terraform_standard_module_structure'
      - '--args=--only=terraform_workspace_remote'
