name: keepalive
on:
  repository_dispatch:
    types: [keepalive]
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  reenable:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate gh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh auth status -h github.com || gh auth login --with-token <<<"$GITHUB_TOKEN"

      - name: Enable all disabled workflows
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mapfile -t DISABLED < <(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/actions/workflows \
            --paginate --jq '.workflows[] | select(.state=="disabled_manually" or .state=="disabled_inactivity") | .path')
          if [ ${#DISABLED[@]} -eq 0 ]; then
            echo "No disabled workflows found."
            exit 0
          fi
          printf 'Will enable:\n'; printf ' - %s\n' "${DISABLED[@]}"
          for wf in "${DISABLED[@]}"; do
            echo "Enabling: $wf"
            gh api -X PUT "/repos/${GITHUB_REPOSITORY}/actions/workflows/${wf}/enable"
          done